import { prisma } from "../prisma";
import type { RegionGroup } from "@prisma/client";

const REGIONS: Array<{
  code: string;
  name: string;
  countryCode: string | null;
  regionGroup: RegionGroup;
  isEuEea: boolean;
  isDefault?: boolean;
  dataResidencySupported?: boolean;
  description?: string;
}> = [
  { code: "DE", name: "Germany", countryCode: "DE", regionGroup: "GERMANY", isEuEea: true, isDefault: true, description: "Germany (EU/EEA, primary data residency region)" },
  { code: "EU", name: "European Union / EEA", countryCode: null, regionGroup: "EU_EEA", isEuEea: true, description: "EU/EEA region group (not a single country)" },
  { code: "FR", name: "France", countryCode: "FR", regionGroup: "EU_EEA", isEuEea: true },
  { code: "NL", name: "Netherlands", countryCode: "NL", regionGroup: "EU_EEA", isEuEea: true },
  { code: "IE", name: "Ireland", countryCode: "IE", regionGroup: "EU_EEA", isEuEea: true },
  { code: "US_EAST", name: "United States (East)", countryCode: "US", regionGroup: "US", isEuEea: false, dataResidencySupported: false },
  { code: "US_WEST", name: "United States (West)", countryCode: "US", regionGroup: "US", isEuEea: false, dataResidencySupported: false },
  { code: "SG", name: "Singapore", countryCode: "SG", regionGroup: "APAC", isEuEea: false, dataResidencySupported: false },
];

const DISCLAIMERS: Array<{ locale: string; title: string; content: string }> = [
  {
    locale: "en",
    title: "AI-Generated Content Notice",
    content:
      "This response was generated by an artificial intelligence system. It may be inaccurate, incomplete, or unsuitable for your specific situation. It does not constitute professional, legal, medical, or financial advice. Please verify important information independently before relying on it.",
  },
  {
    locale: "de",
    title: "Hinweis zu KI-generierten Inhalten",
    content:
      "Diese Antwort wurde von einem KI-System erstellt. Sie kann ungenau, unvollständig oder für Ihre konkrete Situation ungeeignet sein. Sie stellt keine professionelle, rechtliche, medizinische oder finanzielle Beratung dar. Bitte überprüfen Sie wichtige Informationen eigenständig, bevor Sie sich darauf verlassen.",
  },
  {
    locale: "zh",
    title: "人工智能生成内容提示",
    content:
      "此回复由人工智能系统生成，可能不准确、不完整或不适用于您的具体情况。它不构成专业、法律、医疗或财务建议。在依赖重要信息之前，请自行核实。",
  },
];

/**
 * Mock provider processing-region capabilities seeded so the runtime
 * compliance pipeline (region-service.pickProcessingRegion) has real rows to
 * select from in every environment without ever calling a live provider.
 * DE is the primary EU/EEA data-residency region for every provider; EU is
 * added as a secondary non-data-residency EU/EEA capability.
 */
const PROVIDER_REGION_CAPABILITIES: Array<{
  provider: string;
  regionCode: string;
  supportsDataResidency: boolean;
  crossBorderTransfer: boolean;
}> = [
  { provider: "openai", regionCode: "DE", supportsDataResidency: true, crossBorderTransfer: false },
  { provider: "openai", regionCode: "EU", supportsDataResidency: false, crossBorderTransfer: false },
  { provider: "gemini", regionCode: "DE", supportsDataResidency: true, crossBorderTransfer: false },
  { provider: "gemini", regionCode: "EU", supportsDataResidency: false, crossBorderTransfer: false },
  { provider: "deepseek", regionCode: "DE", supportsDataResidency: true, crossBorderTransfer: false },
  { provider: "deepseek", regionCode: "EU", supportsDataResidency: false, crossBorderTransfer: false },
  { provider: "qwen", regionCode: "DE", supportsDataResidency: true, crossBorderTransfer: false },
  { provider: "qwen", regionCode: "EU", supportsDataResidency: false, crossBorderTransfer: false },
  { provider: "claude", regionCode: "DE", supportsDataResidency: true, crossBorderTransfer: false },
  { provider: "claude", regionCode: "EU", supportsDataResidency: false, crossBorderTransfer: false },
];

export async function seedRuntimeCompliance(): Promise<void> {
  for (const region of REGIONS) {
    await prisma.processingRegionRegistry.upsert({
      where: { code: region.code },
      create: {
        code: region.code,
        name: region.name,
        countryCode: region.countryCode,
        regionGroup: region.regionGroup,
        isEuEea: region.isEuEea,
        isDefault: region.isDefault ?? false,
        isActive: true,
        dataResidencySupported: region.dataResidencySupported ?? true,
        description: region.description,
      },
      update: {
        name: region.name,
        countryCode: region.countryCode,
        regionGroup: region.regionGroup,
        isEuEea: region.isEuEea,
        dataResidencySupported: region.dataResidencySupported ?? true,
        description: region.description,
      },
    });
  }

  // Prisma's generated compound-unique `where` input rejects `null` for nullable
  // fields (SQL treats multiple NULLs as distinct, so it can't be used as a lookup
  // key), so the platform-default policy (organizationId/workspaceId both null)
  // can't be upserted via the organizationId_workspaceId_version compound unique.
  // Use findFirst + conditional create/update instead.
  const existingPlatformPolicy = await prisma.compliancePolicy.findFirst({
    where: { organizationId: null, workspaceId: null, version: "1.0.0" },
  });
  if (existingPlatformPolicy) {
    await prisma.compliancePolicy.update({
      where: { id: existingPlatformPolicy.id },
      data: { status: "ACTIVE" },
    });
  } else {
    await prisma.compliancePolicy.create({
      data: {
        organizationId: null,
        workspaceId: null,
        name: "Platform Default Compliance Policy",
        version: "1.0.0",
        status: "ACTIVE",
        riskCategoryDefault: "LIMITED",
        reviewModeDefault: "OPTIONAL",
        transparencyLevelDefault: "BASIC",
        requireAiNotice: true,
        requireGeneratedContentFlag: true,
        requireHumanReview: false,
        requireEuProcessing: false,
        allowCrossBorderTransfer: true,
        allowedRegions: [],
        blockedProviders: [],
        blockedModels: [],
        retentionDays: 365,
        storePromptHash: true,
        storeResponseHash: true,
        storeTokenMetadata: true,
        storeCostMetadata: true,
      },
    });
  }

  for (const disclaimer of DISCLAIMERS) {
    await prisma.complianceDisclaimerVersion.upsert({
      where: { version_locale: { version: "1.0.0", locale: disclaimer.locale } },
      create: {
        version: "1.0.0",
        locale: disclaimer.locale,
        title: disclaimer.title,
        content: disclaimer.content,
        status: "ACTIVE",
      },
      update: {
        title: disclaimer.title,
        content: disclaimer.content,
        status: "ACTIVE",
      },
    });
  }

  await prisma.retentionPolicy.upsert({
    where: { name_version: { name: "default", version: "1.0.0" } },
    create: {
      name: "default",
      version: "1.0.0",
      retentionDays: 365,
      anonymizeAfterDays: 730,
      deleteAfterDays: null,
      appliesTo: "AI_EVENT",
      status: "ACTIVE",
    },
    update: {
      retentionDays: 365,
      anonymizeAfterDays: 730,
      deleteAfterDays: null,
      status: "ACTIVE",
    },
  });

  await seedProviderRegionCapabilities();
}

/**
 * Idempotent by design: looks up an existing active capability row by
 * (provider, regionId, isActive) before creating, so re-running the seed
 * (e.g. on every Preview/Production deploy) never duplicates rows.
 */
async function seedProviderRegionCapabilities(): Promise<void> {
  for (const cap of PROVIDER_REGION_CAPABILITIES) {
    const region = await prisma.processingRegionRegistry.findUnique({ where: { code: cap.regionCode } });
    if (!region) continue;

    const existing = await prisma.providerRegionCapability.findFirst({
      where: { provider: cap.provider, regionId: region.id, isActive: true },
    });
    if (existing) continue;

    await prisma.providerRegionCapability.create({
      data: {
        provider: cap.provider,
        regionId: region.id,
        supportsInference: true,
        supportsProcessing: true,
        supportsDataResidency: cap.supportsDataResidency,
        crossBorderTransfer: cap.crossBorderTransfer,
        transferMechanism: cap.crossBorderTransfer ? "SCCs" : null,
        isActive: true,
      },
    });
  }
}
