import { prisma } from "../prisma";
import type { ComplianceDisclaimerVersion } from "@prisma/client";
import type { SupportedLocale } from "./types";
import { SUPPORTED_LOCALES } from "./types";

/** Static fallback notices used if no ComplianceDisclaimerVersion row is seeded yet (never a legal guarantee claim). */
const STATIC_NOTICES: Record<SupportedLocale, { title: string; content: string }> = {
  en: {
    title: "AI-Generated Content Notice",
    content:
      "This response was generated by an artificial intelligence system. It may be inaccurate, incomplete, or unsuitable for your specific situation. It does not constitute professional, legal, medical, or financial advice. Please verify important information independently before relying on it.",
  },
  de: {
    title: "Hinweis zu KI-generierten Inhalten",
    content:
      "Diese Antwort wurde von einem KI-System erstellt. Sie kann ungenau, unvollständig oder für Ihre konkrete Situation ungeeignet sein. Sie stellt keine professionelle, rechtliche, medizinische oder finanzielle Beratung dar. Bitte überprüfen Sie wichtige Informationen eigenständig, bevor Sie sich darauf verlassen.",
  },
  zh: {
    title: "人工智能生成内容提示",
    content:
      "此回复由人工智能系统生成，可能不准确、不完整或不适用于您的具体情况。它不构成专业、法律、医疗或财务建议。在依赖重要信息之前，请自行核实。",
  },
};

export function isSupportedLocale(locale: string): locale is SupportedLocale {
  return (SUPPORTED_LOCALES as string[]).includes(locale);
}

export function getStaticNotice(locale: SupportedLocale) {
  return STATIC_NOTICES[locale];
}

export async function getActiveDisclaimer(
  locale: SupportedLocale,
  version?: string,
): Promise<ComplianceDisclaimerVersion | null> {
  return prisma.complianceDisclaimerVersion.findFirst({
    where: {
      locale,
      status: "ACTIVE",
      version: version ?? undefined,
    },
    orderBy: { effectiveFrom: "desc" },
  });
}

export type TransparencyNotice = {
  locale: SupportedLocale;
  version: string;
  title: string;
  content: string;
  source: "database" | "static_fallback";
};

export async function getTransparencyNotice(
  locale: string,
  version?: string,
): Promise<TransparencyNotice> {
  const normalizedLocale: SupportedLocale = isSupportedLocale(locale) ? locale : "en";
  const disclaimer = await getActiveDisclaimer(normalizedLocale, version);
  if (disclaimer) {
    return {
      locale: normalizedLocale,
      version: disclaimer.version,
      title: disclaimer.title,
      content: disclaimer.content,
      source: "database",
    };
  }
  const fallback = getStaticNotice(normalizedLocale);
  return {
    locale: normalizedLocale,
    version: version ?? "static",
    title: fallback.title,
    content: fallback.content,
    source: "static_fallback",
  };
}

export async function listDisclaimerVersions(params?: {
  locale?: string;
  status?: "DRAFT" | "ACTIVE" | "RETIRED";
}): Promise<ComplianceDisclaimerVersion[]> {
  return prisma.complianceDisclaimerVersion.findMany({
    where: { locale: params?.locale, status: params?.status },
    orderBy: [{ version: "desc" }, { locale: "asc" }],
  });
}

export type UpsertDisclaimerInput = {
  version: string;
  locale: string;
  title: string;
  content: string;
  status?: "DRAFT" | "ACTIVE" | "RETIRED";
};

export async function upsertDisclaimerVersion(input: UpsertDisclaimerInput): Promise<ComplianceDisclaimerVersion> {
  return prisma.complianceDisclaimerVersion.upsert({
    where: { version_locale: { version: input.version, locale: input.locale } },
    create: {
      version: input.version,
      locale: input.locale,
      title: input.title,
      content: input.content,
      status: input.status ?? "DRAFT",
    },
    update: {
      title: input.title,
      content: input.content,
      status: input.status ?? undefined,
    },
  });
}
