import type { ModelRegistryEntry } from "../types";

const RELEASE = "2025-01-05";

export const QWEN_MODELS: ModelRegistryEntry[] = [
  {
    modelId: "qwen-max",
    provider: "qwen",
    displayName: "Qwen Max",
    contextWindow: 32_000,
    streaming: true,
    functionCalling: true,
    vision: false,
    image: false,
    embedding: false,
    audio: false,
    video: false,
    inputCostPer1M: 1.6,
    outputCostPer1M: 6.4,
    lifecycle: "ACTIVE",
    regionAvailability: ["GLOBAL", "APAC", "CN"],
    euCompliance: false,
    releaseDate: RELEASE,
    deprecatedDate: null,
    replacementModel: null,
  },
  {
    modelId: "qwen-plus",
    provider: "qwen",
    displayName: "Qwen Plus",
    contextWindow: 32_000,
    streaming: true,
    functionCalling: true,
    vision: false,
    image: false,
    embedding: false,
    audio: false,
    video: false,
    inputCostPer1M: 0.4,
    outputCostPer1M: 1.2,
    lifecycle: "ACTIVE",
    regionAvailability: ["GLOBAL", "APAC", "CN"],
    euCompliance: false,
    releaseDate: RELEASE,
    deprecatedDate: null,
    replacementModel: null,
  },
  {
    modelId: "qwen-turbo",
    provider: "qwen",
    displayName: "Qwen Turbo",
    contextWindow: 8_000,
    streaming: true,
    functionCalling: false,
    vision: false,
    image: false,
    embedding: false,
    audio: false,
    video: false,
    inputCostPer1M: 0.05,
    outputCostPer1M: 0.2,
    lifecycle: "ACTIVE",
    regionAvailability: ["GLOBAL", "APAC", "CN"],
    euCompliance: false,
    releaseDate: RELEASE,
    deprecatedDate: null,
    replacementModel: null,
  },
];
