import type { ModelRegistryEntry } from "../types";

const RELEASE = "2025-01-15";

export const OPENAI_MODELS: ModelRegistryEntry[] = [
  {
    modelId: "gpt-5",
    provider: "openai",
    displayName: "GPT-5",
    contextWindow: 128_000,
    streaming: true,
    functionCalling: true,
    vision: true,
    image: false,
    embedding: false,
    audio: false,
    video: false,
    inputCostPer1M: 2.5,
    outputCostPer1M: 10,
    lifecycle: "ACTIVE",
    regionAvailability: ["GLOBAL", "US", "EU"],
    euCompliance: true,
    releaseDate: RELEASE,
    deprecatedDate: null,
    replacementModel: null,
  },
  {
    modelId: "gpt-5-mini",
    provider: "openai",
    displayName: "GPT-5 Mini",
    contextWindow: 128_000,
    streaming: true,
    functionCalling: true,
    vision: true,
    image: false,
    embedding: false,
    audio: false,
    video: false,
    inputCostPer1M: 0.4,
    outputCostPer1M: 1.6,
    lifecycle: "ACTIVE",
    regionAvailability: ["GLOBAL", "US", "EU"],
    euCompliance: true,
    releaseDate: RELEASE,
    deprecatedDate: null,
    replacementModel: null,
  },
  {
    modelId: "text-embedding-3-large",
    provider: "openai",
    displayName: "Text Embedding 3 Large",
    contextWindow: 8_192,
    streaming: false,
    functionCalling: false,
    vision: false,
    image: false,
    embedding: true,
    audio: false,
    video: false,
    inputCostPer1M: 0.13,
    outputCostPer1M: 0,
    lifecycle: "ACTIVE",
    regionAvailability: ["GLOBAL", "US", "EU"],
    euCompliance: true,
    releaseDate: RELEASE,
    deprecatedDate: null,
    replacementModel: null,
  },
];
