(function () {
  const SUPPORTED_PROVIDERS = [
    "openai",
    "anthropic",
    "google",
    "deepseek",
    "qwen",
    "glm",
    "mistral",
    "openrouter",
  ];

  const SUPPORTED_MODELS = [
    "openai/gpt-5",
    "openai/gpt-4.1",
    "openai/gpt-4o",
    "anthropic/claude-4-opus",
    "anthropic/claude-4-sonnet",
    "google/gemini-2.5-pro",
    "google/gemini-2.5-flash",
    "deepseek/deepseek-chat",
    "deepseek/deepseek-reasoner",
    "qwen/qwen-max",
    "qwen/qwen-plus",
    "mistral/mistral-large",
    "openrouter/auto",
  ];

  window.ZWIMA_CONFIG = {
    API_BASE_URL: "https://api.zwima.ai/v1",
    GATEWAY_ENDPOINT: "https://api.zwima.ai/v1/chat/completions",
    MOCK_API_BASE: "/api",
    DB_DRIVER: "mock",
    JWT_ACCESS_TTL_SEC: 900,
    JWT_REFRESH_TTL_SEC: 604800,
    MOCK_DELAY_MIN_MS: 300,
    MOCK_DELAY_MAX_MS: 800,
    MOCK_ERROR_RATE: 0.02,
    DEFAULT_PROVIDER: "openai",
    SUPPORTED_PROVIDERS,
    SUPPORTED_MODELS,
    DEFAULT_LANGUAGE: "en",
    DEFAULT_CURRENCY: "EUR",
    VAT_RATE: 0.19,
    CREDIT_RATE_EUR: 0.1,
    MOCK_DELAY_MS: 120,
    GATEWAY_MODE: "mock",
    GATEWAY_HEALTH_INTERVAL_MS: 30000,
    GATEWAY_TIMEOUT_MOCK_MS: 1200,
    GATEWAY_TIMEOUT_DEVELOPMENT_MS: 45000,
    GATEWAY_TIMEOUT_PRODUCTION_MS: 30000,
    PLAYGROUND_MODE: "real",
    OPENAI_API_KEY: "",
    PROVIDER_API_KEYS: {},
    STRIPE_MODE: "mock",
    STRIPE_PUBLISHABLE_KEY: "",
    STRIPE_SECRET_KEY: "",
    STRIPE_WEBHOOK_SECRET: "",
    AUTH_PROVIDER: "localStorage",
  };
})();
